### ISSUE TITLE
https://github.com/victorpreston/bruteX.git this link doesn't work 

### ISSUE THREAD

**Issue by Kevinsathvik182** [victorpreston/bruteX#9]

**Comment by victorpreston** [comment]
Okay,
What is the issue, do you want to clone the repo or something?

**Comment by Kevinsathvik182** [comment]
It asks username and password and I entered both but it didn't work

**Comment by victorpreston** [comment]
Do you have screenshots?

**Comment by Kevinsathvik182** [comment]
I don't have screenshots but wait I will send you
